# Site Settings
title: CV - Guilherme Antunes
url: 'https://gui-ant.github.io/'

description: A beautiful Jekyll theme for creating resume
theme_skin: blue
chrome_mobile_color: #35869a

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
